<?php
/**
 * Content extracted from the original static DTH pages.
 *
 * Generated by wp-theme/tools/generate-seed.py — do not edit by hand.
 *
 * @package DTH
 */

defined( 'ABSPATH' ) || exit;

/**
 * Seed content for the one-click importer.
 *
 * @return array
 */
function dth_seed_data() {
	return array(
		'asset_base' => 'https://itsupport-owatmaid.github.io/dth-redesign/',
		'slides' => array(
			array(
				'title' => 'สมาคมสภาคนพิการทุกประเภทแห่งประเทศไทย',
				'tag' => 'ยินดีต้อนรับ',
				'subtitle' => 'ส่งเสริมสิทธิ พัฒนาคุณภาพชีวิต และสร้างสังคมที่เท่าเทียมสำหรับทุกคน',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/hero-welcome.png',
			),
		),
		'rights' => array(
			array(
				'title' => 'บัตรคนพิการ',
				'tab_label' => 'บัตรคนพิการ',
				'kicker' => 'เอกสารสำคัญ',
				'content' => 'จุดเริ่มต้นของการเข้าถึงสิทธิพื้นฐานหลายด้าน ทั้งสวัสดิการ การรักษาพยาบาล การศึกษา และสิ่งอำนวยความสะดวก',
				'bullets' => array(
					'เอกสารที่ต้องใช้ในการยื่นคำขอ',
					'ขั้นตอนการออกบัตรและต่ออายุ',
					'หน่วยงานและจุดบริการที่เกี่ยวข้อง',
				),
				'cta_label' => 'ดูสถานพยาบาลที่ออกเอกสารรับรอง',
				'cta_url' => 'https://dth.or.th/knowledge/45-%e0%b8%aa%e0%b8%96%e0%b8%b2%e0%b8%99%e0%b8%9e%e0%b8%a2%e0%b8%b2%e0%b8%9a%e0%b8%b2%e0%b8%a5%e0%b9%80%e0%b8%ad%e0%b8%81%e0%b8%8a%e0%b8%99/',
				'card_badge' => 'ข้อมูลอ้างอิง',
				'card_title' => 'สรุปขั้นตอนทำบัตร',
				'pairs' => array(
					'ผู้มีสิทธิ | คนพิการทุกประเภท',
					'สถานที่ยื่น | พมจ. / รพ.รัฐ',
					'อายุบัตร | 8 ปี',
				),
				'order' => 0,
			),
			array(
				'title' => 'เบี้ยความพิการ',
				'tab_label' => 'เบี้ยความพิการ',
				'kicker' => 'สวัสดิการ',
				'content' => 'สรุปข้อมูลที่ควรรู้ก่อนลงทะเบียนรับสิทธิ รวมถึงเงื่อนไข เอกสาร และการติดตามสถานะการรับเงิน',
				'bullets' => array(
					'คุณสมบัติและเงื่อนไขผู้มีสิทธิ',
					'การยื่นคำขอและช่องทางติดตามผล',
					'ข้อควรตรวจสอบเมื่อเงินยังไม่เข้า',
				),
				'cta_label' => 'ดูอินโฟกราฟิกสิทธิคนพิการ',
				'cta_url' => 'https://dth.or.th/infographic',
				'card_badge' => 'ข้อมูลอ้างอิง',
				'card_title' => 'เบี้ยความพิการ',
				'pairs' => array(
					'ช่องทางยื่น | อบต. / เทศบาล',
					'การจ่าย | รายเดือน',
					'เอกสาร | บัตรคนพิการ, ทะเบียนบ้าน',
				),
				'order' => 1,
			),
			array(
				'title' => 'การศึกษาและการทำงาน',
				'tab_label' => 'การศึกษาและการทำงาน',
				'kicker' => 'โอกาสและอาชีพ',
				'content' => 'รวมสิทธิด้านทุนการศึกษา การฝึกอาชีพ และสิทธิในการจ้างงานที่ช่วยเพิ่มโอกาสและความมั่นคงในระยะยาว',
				'bullets' => array(
					'ทุนและสิทธิทางการศึกษาที่เกี่ยวข้อง',
					'โครงการฝึกอาชีพและพัฒนาทักษะ',
					'สิทธิการจ้างงานตามมาตรา 33/35',
				),
				'cta_label' => 'ค้นหางานคนพิการ (Job Fin Fin)',
				'cta_url' => 'https://www.jobfinfin.com/',
				'card_badge' => 'ข้อมูลอ้างอิง',
				'card_title' => 'การจ้างงาน',
				'pairs' => array(
					'มาตรา 33 | จ้างงานโดยตรง',
					'มาตรา 35 | สัมปทาน/ฝึกงาน',
					'หน่วยงาน | กรมการจัดหางาน',
				),
				'order' => 2,
			),
			array(
				'title' => 'ร้องเรียนและประสานช่วยเหลือ',
				'tab_label' => 'ร้องเรียนและช่วยเหลือ',
				'kicker' => 'ขอความช่วยเหลือ',
				'content' => 'เมื่อเกิดปัญหาในการเข้าถึงสิทธิ การบริการ หรือสวัสดิการ ควรมีช่องทางที่ชัดเจนสำหรับแจ้งเรื่องและติดตามผล',
				'bullets' => array(
					'ช่องทางร้องเรียนเมื่อไม่ได้รับสิทธิ',
					'การประสานหน่วยงานที่เกี่ยวข้อง',
					'แนวทางเตรียมข้อมูลก่อนแจ้งเรื่อง',
				),
				'cta_label' => 'ดูช่องทางติดต่อ',
				'cta_url' => '#contact',
				'card_badge' => 'Quick Access',
				'card_title' => 'ช่องทางติดต่อ',
				'pairs' => array(
					'สายด่วน | 1479',
					'โทรสมาคม | 02-354-4260',
					'อีเมล | disabilitiesth@gmail.com',
				),
				'order' => 3,
			),
		),
		'faqs' => array(
			array(
				'title' => 'ขอเอกสารรับรองความพิการได้ที่สถานพยาบาลใดบ้าง?',
				'link' => 'https://dth.or.th/knowledge/45-%e0%b8%aa%e0%b8%96%e0%b8%b2%e0%b8%99%e0%b8%9e%e0%b8%a2%e0%b8%b2%e0%b8%9a%e0%b8%b2%e0%b8%a5%e0%b9%80%e0%b8%ad%e0%b8%81%e0%b8%8a%e0%b8%99/',
				'order' => 0,
			),
			array(
				'title' => 'ลงทะเบียนรับเบี้ยความพิการได้ที่ไหน?',
				'link' => '#rights',
				'order' => 1,
			),
			array(
				'title' => 'สิทธิการจ้างงานตามมาตรา 33 และ 35 ต่างกันอย่างไร?',
				'link' => '#rights',
				'order' => 2,
			),
			array(
				'title' => 'หากไม่ได้รับสิทธิที่ควรได้ จะร้องเรียนได้ทางใด?',
				'link' => '#contact',
				'order' => 3,
			),
		),
		'partners' => array(
			array(
				'title' => 'สมาคมคนตาบอดแห่งประเทศไทย',
				'link' => 'https://www.facebook.com/TabodThai?locale=th_TH',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/members/blind.png',
				'group' => 'members',
				'order' => 0,
			),
			array(
				'title' => 'สมาคมผู้ปกครองคนพิการทางสติปัญญาแห่งประเทศไทย',
				'link' => 'https://www.facebook.com/pikarnpanya.bangkok?locale=th_TH',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/members/intellectual.jpg',
				'group' => 'members',
				'order' => 1,
			),
			array(
				'title' => 'สมาคมผู้ปกครองบุคคลออทิซึม (ไทย)',
				'link' => 'https://www.facebook.com/APTAutismThailand?locale=th_TH',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/members/autism.jpg',
				'group' => 'members',
				'order' => 2,
			),
			array(
				'title' => 'สมาคมคนหูหนวกแห่งประเทศไทย',
				'link' => 'https://www.facebook.com/nadthailand?locale=th_TH',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/members/deaf.png',
				'group' => 'members',
				'order' => 3,
			),
			array(
				'title' => 'สมาคมคนพิการแห่งประเทศไทย',
				'link' => 'https://www.facebook.com/disabledofthailand?locale=th_TH',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/members/physical.png',
				'group' => 'members',
				'order' => 4,
			),
			array(
				'title' => 'สมาคมเพื่อผู้บกพร่องทางจิตแห่งประเทศไทย',
				'link' => 'https://www.facebook.com/amidmh.th?locale=th_TH',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/members/mental.jpg',
				'group' => 'members',
				'order' => 5,
			),
			array(
				'title' => 'กระทรวงการพัฒนาสังคมและความมั่นคงของมนุษย์',
				'link' => 'https://www.m-society.go.th/home.php',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/04/logo-01.png',
				'group' => 'government',
				'order' => 0,
			),
			array(
				'title' => 'กรมส่งเสริมและพัฒนาคุณภาพชีวิตคนพิการ',
				'link' => 'https://dep.go.th/th/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/04/logo-04.png',
				'group' => 'government',
				'order' => 1,
			),
			array(
				'title' => 'สำนักงานหลักประกันสุขภาพแห่งชาติ (สปสช.)',
				'link' => 'https://www.nhso.go.th',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/04/logo-05.png',
				'group' => 'government',
				'order' => 2,
			),
			array(
				'title' => 'สำนักงานกองทุนสนับสนุนการสร้างเสริมสุขภาพ (สสส.)',
				'link' => 'https://www.thaihealth.or.th',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/04/logo-06.png',
				'group' => 'government',
				'order' => 3,
			),
			array(
				'title' => 'กรมการจัดหางาน',
				'link' => 'https://www.doe.go.th/prd/main',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/04/logo-12.png',
				'group' => 'government',
				'order' => 4,
			),
			array(
				'title' => 'กระทรวงศึกษาธิการ',
				'link' => 'https://www.moe.go.th',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/04/logo-13.png',
				'group' => 'government',
				'order' => 5,
			),
			array(
				'title' => 'คณะกรรมการว่าด้วยสิทธิคนพิการแห่งสหประชาชาติ',
				'link' => 'https://www.ohchr.org/en/treaty-bodies/crpd',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/CRPD.png',
				'group' => 'government',
				'order' => 6,
			),
			array(
				'title' => 'International Disability Alliance',
				'link' => 'https://www.internationaldisabilityalliance.org/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/IDA-Logo.png',
				'group' => 'government',
				'order' => 7,
			),
		),
		'people' => array(
			array(
				'title' => 'นายวิทยุต บุนนาค',
				'position' => 'นายกสมาคมสภาคนพิการทุกประเภทแห่งประเทศไทย/ประธานฝ่ายศิลปะ วัฒนธรรม และภาษา',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/รูปนายก/cut/board-witthayut.png',
				'group' => 'board-executive',
				'order' => 0,
			),
			array(
				'title' => 'นายเอกกมล แพทยานันท์',
				'position' => 'อุปนายก คนที่ 1/เหรัญญิก/ประธานฝ่ายต่างประเทศและขับเคลื่อนนโยบายสาธารณะ',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/รูปนายก/cut/board-ekkamon.png',
				'group' => 'board-executive',
				'order' => 1,
			),
			array(
				'title' => 'นายสุชาติ โอวาทวรรณสกุล',
				'position' => 'อุปนายก คนที่ 2',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/รูปนายก/cut/board-suchart.png',
				'group' => 'board-executive',
				'order' => 2,
			),
			array(
				'title' => 'นายชูศักดิ์ จันทยานนท์',
				'position' => 'อุปนายก คนที่ 3/เลขาธิการ/ประธานฝ่ายวิสาหกิจเพื่อสังคม',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/รูปนายก/cut/board-choosak.png',
				'group' => 'board-executive',
				'order' => 3,
			),
			array(
				'title' => 'นางนุชจารี คล้ายสุวรรณ',
				'position' => 'อุปนายก คนที่ 4/ปฏิคม',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/รูปนายก/cut/board-nutcharee.png',
				'group' => 'board-executive',
				'order' => 4,
			),
			array(
				'title' => 'นายศุภชีพ ดิษเทศ',
				'position' => 'อุปนายก คนที่ 5/นายทะเบียน',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/รูปนายก/cut/board-suphachip.png',
				'group' => 'board-executive',
				'order' => 5,
			),
			array(
				'title' => 'นางกัณฐมณี พฤกษะวัน',
				'position' => 'กรรมการ/ประธานฝ่ายประชาสัมพันธ์และสื่อสารองค์กร',
				'image' => '',
				'group' => 'board',
				'order' => 0,
			),
			array(
				'title' => 'นายกิตติพงษ์ หาดทวายกาญจน์',
				'position' => 'กรรมการ/ประธานฝ่ายการท่องเที่ยวและกีฬา',
				'image' => '',
				'group' => 'board',
				'order' => 1,
			),
			array(
				'title' => 'นายชัชชัย วิจิตรจรรยา',
				'position' => 'กรรมการ/ประธานฝ่ายเทคโนโลยีสารสนเทศและการสื่อสาร',
				'image' => '',
				'group' => 'board',
				'order' => 2,
			),
			array(
				'title' => 'นางสาวญาณี ชีวะเจริญ',
				'position' => 'กรรมการ/ประธานฝ่ายจิตอาสาและพัฒนาศักยภาพ',
				'image' => '',
				'group' => 'board',
				'order' => 3,
			),
			array(
				'title' => 'นายเทวพงษ์ พวงเพชร',
				'position' => 'กรรมการ/ประธานฝ่ายส่งเสริมและพัฒนาผู้นำคนพิการ',
				'image' => '',
				'group' => 'board',
				'order' => 4,
			),
			array(
				'title' => 'นายปราโมทย์ ธรรมสโรช',
				'position' => 'กรรมการ/ประธานฝ่ายการศึกษา',
				'image' => '',
				'group' => 'board',
				'order' => 5,
			),
			array(
				'title' => 'นายพลทร ขุนสะอาด',
				'position' => 'กรรมการ/ประธานฝ่ายเด็กและเยาวชน',
				'image' => '',
				'group' => 'board',
				'order' => 6,
			),
			array(
				'title' => 'นายภัทรพันธุ์ กฤษณา',
				'position' => 'กรรมการ/ประธานฝ่ายสิ่งอำนวยความสะดวกสำหรับคนพิการ',
				'image' => '',
				'group' => 'board',
				'order' => 7,
			),
			array(
				'title' => 'นางวาสนา สำลีรัตน์',
				'position' => 'กรรมการ/ประธานฝ่ายสวัสดิการ',
				'image' => '',
				'group' => 'board',
				'order' => 8,
			),
			array(
				'title' => 'นายสมชาย ปัญญ์เอกวงศ์',
				'position' => 'กรรมการ/ประธานฝ่ายกฎหมายและสิทธิมนุษยชน',
				'image' => '',
				'group' => 'board',
				'order' => 9,
			),
			array(
				'title' => 'นายสุบิน แบขุนทด',
				'position' => 'กรรมการ/ประธานฝ่ายส่งเสริมอาชีพและการจ้างงาน',
				'image' => '',
				'group' => 'board',
				'order' => 10,
			),
			array(
				'title' => 'นางสาวอรุณวดี ลิ้มอังกูร',
				'position' => 'กรรมการ/ประธานฝ่ายการแพทย์',
				'image' => '',
				'group' => 'board',
				'order' => 11,
			),
			array(
				'title' => 'นางอรุณี ลิ้มมณี',
				'position' => 'กรรมการ/ประธานฝ่ายสตรีและกลุ่มเป้าหมายพิเศษ',
				'image' => '',
				'group' => 'board',
				'order' => 12,
			),
			array(
				'title' => 'นางกัญญาวีร์ แขวงโสภา',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 13,
			),
			array(
				'title' => 'นางสาวกิจจาพร ชื่นบุญ',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 14,
			),
			array(
				'title' => 'นางสาวฐิติพร พริ้งเพลิด',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 15,
			),
			array(
				'title' => 'นางฑิฆัมพร บุญศรี',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 16,
			),
			array(
				'title' => 'นางณัชชา กู้สุจริต',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 17,
			),
			array(
				'title' => 'นางสาวปรียาพรรณ มีษา',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 18,
			),
			array(
				'title' => 'นางสาวพัตสุณี สุรินทร์',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 19,
			),
			array(
				'title' => 'นายภักดี พิกุลหอม',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 20,
			),
			array(
				'title' => 'นางวันเพ็ญ นิภานันท์',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 21,
			),
			array(
				'title' => 'นายสามารถ ห้องกระจก',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 22,
			),
			array(
				'title' => 'นายสุรเชษฐ์ คำนวล',
				'position' => 'กรรมการ',
				'image' => '',
				'group' => 'board',
				'order' => 23,
			),
			array(
				'title' => 'นางสาวจรรยา บัวศร',
				'position' => 'ผู้อำนวยการสำนักงาน',
				'image' => '',
				'group' => 'staff',
				'order' => 0,
			),
			array(
				'title' => 'นายรัตน์ กิจธรรม',
				'position' => 'ผู้อำนวยการฝ่ายต่างประเทศและขับเคลื่อนนโยบายสาธารณะ',
				'image' => '',
				'group' => 'staff',
				'order' => 1,
			),
			array(
				'title' => 'นางสาวญาณิกา อักษรนำ',
				'position' => 'ผู้อำนวยการฝ่ายกิจการภูมิภาคและองค์กรท้องถิ่น',
				'image' => '',
				'group' => 'staff',
				'order' => 2,
			),
			array(
				'title' => 'นางสาววาริสา ทรัพย์ประดิษฐ',
				'position' => 'ผู้อำนวยการฝ่ายวิจัยและพัฒนา',
				'image' => '',
				'group' => 'staff',
				'order' => 3,
			),
			array(
				'title' => 'นางสาวศิริรัช ไชยรัตน์',
				'position' => 'หัวหน้าฝ่ายประสานงานส่วนกลาง',
				'image' => '',
				'group' => 'staff',
				'order' => 4,
			),
			array(
				'title' => 'นางสาวรตินันท์ เมฆฉาย',
				'position' => 'ผู้ช่วยอำนวยการสำนักงานและกิจการภูมิภาค',
				'image' => '',
				'group' => 'staff',
				'order' => 5,
			),
			array(
				'title' => 'นางสาวสวรรยา ปุนินานนท์',
				'position' => 'ผู้ช่วยฝ่ายประสานงานส่วนกลาง',
				'image' => '',
				'group' => 'staff',
				'order' => 6,
			),
			array(
				'title' => 'นายสุนทร สุขชา',
				'position' => 'เจ้าหน้าที่ฝ่ายกฎหมาย',
				'image' => '',
				'group' => 'staff',
				'order' => 7,
			),
			array(
				'title' => 'Mr. Nathaniel Ross',
				'position' => 'Law & Policy Officer',
				'image' => '',
				'group' => 'staff',
				'order' => 8,
			),
			array(
				'title' => 'นางสาวปัณณรัตน์ อัคราสิริภัสร์',
				'position' => 'เจ้าหน้าที่ฝ่ายการเงิน',
				'image' => '',
				'group' => 'staff',
				'order' => 9,
			),
			array(
				'title' => 'นางสาวเจนจิรา ไตรวรรณ์',
				'position' => 'เจ้าหน้าที่ฝ่ายสื่อสารสาธารณะ',
				'image' => '',
				'group' => 'staff',
				'order' => 10,
			),
			array(
				'title' => 'นายโมทน์ อุเทนสุต',
				'position' => 'เจ้าหน้าที่ฝ่ายบริหารงานทั่วไป',
				'image' => '',
				'group' => 'staff',
				'order' => 11,
			),
		),
		'provinces' => array(
			array(
				'title' => 'เชียงใหม่',
				'chair' => 'ผศ.ดวงพร อ่อนหวาน',
				'disability' => 'ออทิสติก',
				'phone' => '089-7004396',
				'region' => 'ภาคเหนือ',
				'order' => 0,
			),
			array(
				'title' => 'เชียงราย',
				'chair' => 'นายพรศักดิ์ สีสม',
				'disability' => 'สายตา',
				'phone' => '061-9724715',
				'region' => 'ภาคเหนือ',
				'order' => 1,
			),
			array(
				'title' => 'แพร่',
				'chair' => 'นางสาวนิตยา ท้าวทา',
				'disability' => 'การได้ยิน',
				'phone' => '098-3603252',
				'region' => 'ภาคเหนือ',
				'order' => 2,
			),
			array(
				'title' => 'แม่ฮ่องสอน',
				'chair' => 'นายเรวัตร วงศ์ศักดิ์ศรี',
				'disability' => 'ออทิสติก',
				'phone' => '081-9982268',
				'region' => 'ภาคเหนือ',
				'order' => 3,
			),
			array(
				'title' => 'กำแพงเพชร',
				'chair' => 'นายสีมาลา เอี่ยมศรี',
				'disability' => 'เคลื่อนไหว',
				'phone' => '086-9378535',
				'region' => 'ภาคเหนือ',
				'order' => 4,
			),
			array(
				'title' => 'ตาก',
				'chair' => 'พันโทสุชาติ โท่มาก',
				'disability' => 'สติปัญญา',
				'phone' => '091-0035708',
				'region' => 'ภาคเหนือ',
				'order' => 5,
			),
			array(
				'title' => 'นครสวรรค์',
				'chair' => 'นายนิภัทร ทองเงิน',
				'disability' => 'การได้ยิน',
				'phone' => '061-6527696',
				'region' => 'ภาคเหนือ',
				'order' => 6,
			),
			array(
				'title' => 'พะเยา',
				'chair' => 'นายเต็ม มณีวรรณ์',
				'disability' => 'จิตใจ',
				'phone' => '085-7070723',
				'region' => 'ภาคเหนือ',
				'order' => 7,
			),
			array(
				'title' => 'พิจิตร',
				'chair' => 'นางสาวรินทร์ลภัส บัณฑิตสกุลชัย',
				'disability' => 'เคลื่อนไหว',
				'phone' => '095-453 0899',
				'region' => 'ภาคเหนือ',
				'order' => 8,
			),
			array(
				'title' => 'พิษณุโลก',
				'chair' => 'นายอิศรุจน์ อิศรางกรู ณ อยุธยา',
				'disability' => 'การได้ยิน',
				'phone' => '095-6295107',
				'region' => 'ภาคเหนือ',
				'order' => 9,
			),
			array(
				'title' => 'ลำปาง',
				'chair' => 'นางกิตติยา รัตนพรรณ',
				'disability' => 'สติปัญญา',
				'phone' => '096-6988368',
				'region' => 'ภาคเหนือ',
				'order' => 10,
			),
			array(
				'title' => 'ลำพูน',
				'chair' => 'นางชลธิชา พิพัฒนไมตรี',
				'disability' => 'การได้ยิน',
				'phone' => '083-2049153',
				'region' => 'ภาคเหนือ',
				'order' => 11,
			),
			array(
				'title' => 'สุโขทัย',
				'chair' => 'นายสิทธิพงษ์ คงประยูร',
				'disability' => 'การได้ยิน',
				'phone' => '062-1576202',
				'region' => 'ภาคเหนือ',
				'order' => 12,
			),
			array(
				'title' => 'อุตรดิตถ์',
				'chair' => 'นายสมพล พงษ์พันธ์',
				'disability' => 'การได้ยิน',
				'phone' => '082-1700425',
				'region' => 'ภาคเหนือ',
				'order' => 13,
			),
			array(
				'title' => 'อุทัยธานี',
				'chair' => 'นายสุนันท์ แซ่โล้ว',
				'disability' => 'เคลื่อนไหว',
				'phone' => '097-9311146',
				'region' => 'ภาคเหนือ',
				'order' => 14,
			),
			array(
				'title' => 'เลย',
				'chair' => 'นายสีหนารถ อินทร์จา',
				'disability' => 'สายตา',
				'phone' => '087-0454146',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 0,
			),
			array(
				'title' => 'กาฬสินธุ์',
				'chair' => 'นายฉลาด นะตะวัน',
				'disability' => 'สายตา',
				'phone' => '080-6232328',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 1,
			),
			array(
				'title' => 'ขอนแก่น',
				'chair' => 'นายอาทิตย์ เกตุโท',
				'disability' => 'การได้ยิน',
				'phone' => '098-5906696',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 2,
			),
			array(
				'title' => 'ชัยภูมิ',
				'chair' => 'นางจินตนา หล้าแก้ว',
				'disability' => 'ออทิสติก',
				'phone' => '080-4667837',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 3,
			),
			array(
				'title' => 'นครพนม',
				'chair' => 'นางสาวนิลวรรณ ปิติพัฒน์',
				'disability' => 'การได้ยิน',
				'phone' => '092-3155549',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 4,
			),
			array(
				'title' => 'นครราชสีมา',
				'chair' => 'นางสาวรัตนา สีนาค',
				'disability' => 'การได้ยิน',
				'phone' => '091-8280793',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 5,
			),
			array(
				'title' => 'บึงกาฬ',
				'chair' => 'นางผ่องศรี โพธิเสน',
				'disability' => 'เคลื่อนไหว',
				'phone' => '090-7990622',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 6,
			),
			array(
				'title' => 'บุรีรัมย์',
				'chair' => 'นายวิสิทธิ์ จันทร์สิงห์',
				'disability' => 'จิตใจ',
				'phone' => '099-0757671',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 7,
			),
			array(
				'title' => 'มหาสารคาม',
				'chair' => 'นายทรงยศ วันสา',
				'disability' => 'การได้ยิน',
				'phone' => '098-6174534',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 8,
			),
			array(
				'title' => 'มุกดาหาร',
				'chair' => 'นายสุชาติ คนเพียร',
				'disability' => 'สายตา',
				'phone' => '098-5595672',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 9,
			),
			array(
				'title' => 'ยโสธร',
				'chair' => 'นางสาวชุติมา ศรีทราไชย',
				'disability' => 'เคลื่อนไหว',
				'phone' => '081-8787619',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 10,
			),
			array(
				'title' => 'ร้อยเอ็ด',
				'chair' => 'นางศุภนุช เชิงหอม',
				'disability' => 'สติปัญญา',
				'phone' => '099-5087991',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 11,
			),
			array(
				'title' => 'ศรีสะเกษ',
				'chair' => 'นายจีระศักดิ์ พรหมทา',
				'disability' => 'การได้ยิน',
				'phone' => '097-1466033',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 12,
			),
			array(
				'title' => 'สกลนคร',
				'chair' => 'นายปัญญา จันทะเสน',
				'disability' => 'สายตา',
				'phone' => '099-6678322',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 13,
			),
			array(
				'title' => 'สุรินทร์',
				'chair' => 'นางสาวจุฑาภัทร โนนใหญ่',
				'disability' => 'สติปัญญา',
				'phone' => '062-4647081',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 14,
			),
			array(
				'title' => 'หนองคาย',
				'chair' => 'นายชยุต มณีรัตน์',
				'disability' => 'เคลื่อนไหว',
				'phone' => '084-9576554',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 15,
			),
			array(
				'title' => 'อำนาจเจริญ',
				'chair' => 'นางนุจรินทร์ ถือสัตย์',
				'disability' => 'สติปัญญา',
				'phone' => '098-5849345',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 16,
			),
			array(
				'title' => 'อุดรธานี',
				'chair' => 'นางสาวยุวดี เพ็ชรพลอย',
				'disability' => 'การได้ยิน',
				'phone' => '093-8209958',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 17,
			),
			array(
				'title' => 'อุบลราชธานี',
				'chair' => 'นางสาวชนิกูล สวัสดิ์พันธ์',
				'disability' => 'เคลื่อนไหว',
				'phone' => '089-0984566',
				'region' => 'ภาคตะวันออกเฉียงเหนือ (อีสาน)',
				'order' => 18,
			),
			array(
				'title' => 'เพชรบุรี',
				'chair' => 'นางสาวศิรินันท์ นิลสุข',
				'disability' => 'เคลื่อนไหว',
				'phone' => '089-9139713',
				'region' => 'ภาคกลาง',
				'order' => 0,
			),
			array(
				'title' => 'กรุงเทพมหานคร',
				'chair' => 'นางสาวเพ็ญนภา นันทดิลก',
				'disability' => 'สติปัญญา',
				'phone' => '081-8273475',
				'region' => 'ภาคกลาง',
				'order' => 1,
			),
			array(
				'title' => 'จันทบุรี',
				'chair' => 'นางยุพยง วณอังศุธร',
				'disability' => 'การได้ยิน',
				'phone' => '084-9288762',
				'region' => 'ภาคกลาง',
				'order' => 2,
			),
			array(
				'title' => 'ฉะเชิงเทรา',
				'chair' => 'นางนภาพร สวนเลิศ',
				'disability' => 'การได้ยิน',
				'phone' => '095-9066896',
				'region' => 'ภาคกลาง',
				'order' => 3,
			),
			array(
				'title' => 'ชลบุรี',
				'chair' => 'นายณรงค์ ไปวันเสาร์',
				'disability' => 'เคลื่อนไหว',
				'phone' => '081-6691111',
				'region' => 'ภาคกลาง',
				'order' => 4,
			),
			array(
				'title' => 'นครนายก',
				'chair' => 'นางสาวนารีรัตน์ รสหอม',
				'disability' => 'สายตา',
				'phone' => '089-0955209',
				'region' => 'ภาคกลาง',
				'order' => 5,
			),
			array(
				'title' => 'นครปฐม',
				'chair' => 'นางจินดา ดีสุกใส',
				'disability' => 'จิตใจ',
				'phone' => '095-5482262',
				'region' => 'ภาคกลาง',
				'order' => 6,
			),
			array(
				'title' => 'นนทบุรี',
				'chair' => 'นายพรทร ขุนสะอาด',
				'disability' => 'สติปัญญา',
				'phone' => '081-9289268',
				'region' => 'ภาคกลาง',
				'order' => 7,
			),
			array(
				'title' => 'ปทุมธานี',
				'chair' => 'นางวาสนา สำลีรัตน์',
				'disability' => 'ออทิสติก',
				'phone' => '089-7817050',
				'region' => 'ภาคกลาง',
				'order' => 8,
			),
			array(
				'title' => 'ปราจีนบุรี',
				'chair' => 'นายสุชาติ ห้วยแก้ว',
				'disability' => 'สายตา',
				'phone' => '083-0498744',
				'region' => 'ภาคกลาง',
				'order' => 9,
			),
			array(
				'title' => 'พระนครศรีอยุธยา',
				'chair' => 'นางสาวชุตินันท์ พุ่มพฤกษ์',
				'disability' => 'จิตใจ',
				'phone' => '099-1748529',
				'region' => 'ภาคกลาง',
				'order' => 10,
			),
			array(
				'title' => 'ระยอง',
				'chair' => 'นายสมศักดิ์ จันทร์พราหมณ์',
				'disability' => 'เคลื่อนไหว',
				'phone' => '087-0396633',
				'region' => 'ภาคกลาง',
				'order' => 11,
			),
			array(
				'title' => 'ราชบุรี',
				'chair' => 'นางวรวรรณ องค์อภิชาติ',
				'disability' => 'การได้ยิน',
				'phone' => '092-2522404',
				'region' => 'ภาคกลาง',
				'order' => 12,
			),
			array(
				'title' => 'สมุทรปราการ',
				'chair' => 'ดร. สิงห์คำ มณีจันสุข',
				'disability' => 'เคลื่อนไหว',
				'phone' => '081-8319544',
				'region' => 'ภาคกลาง',
				'order' => 13,
			),
			array(
				'title' => 'สมุทรสงคราม',
				'chair' => 'นางนฤมล เอมมาวัฒน์',
				'disability' => 'สติปัญญา',
				'phone' => '080-2315246',
				'region' => 'ภาคกลาง',
				'order' => 14,
			),
			array(
				'title' => 'สมุทรสาคร',
				'chair' => 'นายเกษม จันทร์คง',
				'disability' => 'เคลื่อนไหว',
				'phone' => '089-2225372',
				'region' => 'ภาคกลาง',
				'order' => 15,
			),
			array(
				'title' => 'สระแก้ว',
				'chair' => 'นายวรพงศ์ วงษ์ศรีแก้ว',
				'disability' => 'การได้ยิน',
				'phone' => '064-7795571',
				'region' => 'ภาคกลาง',
				'order' => 16,
			),
			array(
				'title' => 'สิงห์บุรี',
				'chair' => 'นายเฉลิมพร มั่นคง',
				'disability' => 'การได้ยิน',
				'phone' => '091-7814569',
				'region' => 'ภาคกลาง',
				'order' => 17,
			),
			array(
				'title' => 'อ่างทอง',
				'chair' => 'นายทศพร บินกาซัน',
				'disability' => 'จิตใจ',
				'phone' => '080-1098396',
				'region' => 'ภาคกลาง',
				'order' => 18,
			),
			array(
				'title' => 'กระบี่',
				'chair' => 'นายประดิษฐ์ แซ่ด่าน',
				'disability' => 'สายตา',
				'phone' => '088-7906649',
				'region' => 'ภาคใต้',
				'order' => 0,
			),
			array(
				'title' => 'ชุมพร',
				'chair' => 'นางจินตนา เล่งระบำ',
				'disability' => 'สติปัญญา',
				'phone' => '095-0157993',
				'region' => 'ภาคใต้',
				'order' => 1,
			),
			array(
				'title' => 'ตรัง',
				'chair' => 'นางณัชชา กู้สุจริต',
				'disability' => 'การได้ยิน',
				'phone' => '081-0822459',
				'region' => 'ภาคใต้',
				'order' => 2,
			),
			array(
				'title' => 'นครศรีธรรมราช',
				'chair' => 'นายธนภณ ภควัตเกศกุล',
				'disability' => 'ออทิสติก',
				'phone' => '081-8090864',
				'region' => 'ภาคใต้',
				'order' => 3,
			),
			array(
				'title' => 'นราธิวาส',
				'chair' => 'นายอับดุลเลาะ มะจำ',
				'disability' => 'สายตา',
				'phone' => '084-3968238',
				'region' => 'ภาคใต้',
				'order' => 4,
			),
			array(
				'title' => 'ปัตตานี',
				'chair' => 'นายอาหามะ มะหาจิ',
				'disability' => 'สายตา',
				'phone' => '080-7086963',
				'region' => 'ภาคใต้',
				'order' => 5,
			),
			array(
				'title' => 'พังงา',
				'chair' => 'นายสุรเชษฐ์ แอนุ้ย',
				'disability' => 'การได้ยิน',
				'phone' => '096-8107143',
				'region' => 'ภาคใต้',
				'order' => 6,
			),
			array(
				'title' => 'พัทลุง',
				'chair' => 'นายบุญสิทธิ์ หนูแสง',
				'disability' => 'สายตา',
				'phone' => '085-1211005',
				'region' => 'ภาคใต้',
				'order' => 7,
			),
			array(
				'title' => 'ภูเก็ต',
				'chair' => 'นางณัจฉรียา ชูแก้ว',
				'disability' => 'สติปัญญา',
				'phone' => '082-8243514',
				'region' => 'ภาคใต้',
				'order' => 8,
			),
			array(
				'title' => 'ยะลา',
				'chair' => 'นางสาวซูรียะห์ เซ็งยี',
				'disability' => 'การได้ยิน',
				'phone' => '061-6805402',
				'region' => 'ภาคใต้',
				'order' => 9,
			),
			array(
				'title' => 'ระนอง',
				'chair' => 'นายกฤตภาส เอกโอฬารกุล',
				'disability' => 'ออทิสติก',
				'phone' => '062-5364449',
				'region' => 'ภาคใต้',
				'order' => 10,
			),
			array(
				'title' => 'สงขลา',
				'chair' => 'นายประเสริฐ ณรงค์กูล',
				'disability' => 'การได้ยิน',
				'phone' => '080-1475486',
				'region' => 'ภาคใต้',
				'order' => 11,
			),
			array(
				'title' => 'สตูล',
				'chair' => 'นายอภิเดช พรหมเมฆ',
				'disability' => 'การได้ยิน',
				'phone' => '088-7854022',
				'region' => 'ภาคใต้',
				'order' => 12,
			),
			array(
				'title' => 'สุราษฏร์ธานี',
				'chair' => 'นายจำนงค์ เต๊ะปู',
				'disability' => 'การได้ยิน',
				'phone' => '089-8673192',
				'region' => 'ภาคใต้',
				'order' => 13,
			),
		),
		'news' => array(
			array(
				'title' => 'เผยแพร่ข้อบังคับสมาคมสภาคนพิการทุกประเภทฯ พ.ศ. 2560 (แก้ไขเพิ่มเติม 2565)',
				'excerpt' => 'ดาวน์โหลดข้อบังคับสมาคมฉบับปรับปรุงล่าสุดได้แล้ว ทั้งรูปแบบ PDF และ Word',
				'url' => 'https://dth.or.th/wp-content/uploads/2024/09/ข้อบังคับสภาคนพิการพ.ศ.25602565.pdf',
				'image' => '',
				'cats' => array(
					'pr',
				),
				'date_label' => '16-09-2567',
				'views' => '',
				'order' => 0,
			),
			array(
				'title' => 'การประชุมสมัชชาคนพิการแห่งชาติ',
				'excerpt' => 'ร่วมขับเคลื่อนนโยบายและสิทธิคนพิการไปด้วยกัน ติดตามรายละเอียดกิจกรรมล่าสุดผ่าน Facebook ของสมาคม',
				'url' => 'https://www.facebook.com/share/1Ez81X9Yjh/',
				'image' => 'https://dth.or.th/wp-content/uploads/2024/09/หน้าปกเว็บไซต์ประชุมสมัชชา-ยาว.png',
				'cats' => array(
					'activity',
				),
				'date_label' => 'ติดตามกำหนดการผ่านเพจ',
				'views' => '',
				'order' => 1,
			),
			array(
				'title' => 'เส้นเลือดขอด อีกหนึ่งโรคยอดฮิตของวัยทำงาน',
				'excerpt' => 'เส้นเลือดขอด อีกหนึ่งโรคยอดฮิตของวัยทำงาน เมื่อเกิดขึ้นแล้วจะทำให้มีอาการปวด จา…',
				'url' => 'https://dth.or.th/knowledge/%e0%b9%80%e0%b8%aa%e0%b9%89%e0%b8%99%e0%b9%80%e0%b8%a5%e0%b8%b7%e0%b8%ad%e0%b8%94%e0%b8%82%e0%b8%ad%e0%b8%94/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/279270879_1630628107293643_3234477952132787000_n-300x212.jpg',
				'cats' => array(
					'knowledge',
					'health',
				),
				'date_label' => '25-07-2565',
				'views' => '2,877',
				'order' => 2,
			),
			array(
				'title' => 'กลุ่มไหนเสี่ยงมีภาวะข้อสะโพกเสื่อม',
				'excerpt' => 'กลุ่มไหนเสี่ยงมีภาวะข้อสะโพกเสื่อม ข้อสะโพกเป็นอวัยวะที่ใช้ในการช่วยพยุงและรับน้…',
				'url' => 'https://dth.or.th/knowledge/%e0%b8%a0%e0%b8%b2%e0%b8%a7%e0%b8%b0%e0%b8%82%e0%b9%89%e0%b8%ad%e0%b8%aa%e0%b8%b0%e0%b9%82%e0%b8%9e%e0%b8%81%e0%b9%80%e0%b8%aa%e0%b8%b7%e0%b9%88%e0%b8%ad%e0%b8%a1/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/กลุ่มไหนเสี่ยงมีภาวะข้อสะโพกเสื่อม-300x212.jpg',
				'cats' => array(
					'knowledge',
					'health',
				),
				'date_label' => '25-07-2565',
				'views' => '2,821',
				'order' => 3,
			),
			array(
				'title' => 'การเข้าสังคมของบุคคลออทิสติก หลังสถานการณ์โควิด-19',
				'excerpt' => 'การเข้าสังคมของบุคคลออทิสติก หลังสถานการณ์โควิด-19 อัษฎากรณ์ ขันตี …',
				'url' => 'https://dth.or.th/knowledge/%e0%b8%81%e0%b8%b2%e0%b8%a3%e0%b9%80%e0%b8%82%e0%b9%89%e0%b8%b2%e0%b8%aa%e0%b8%b1%e0%b8%87%e0%b8%84%e0%b8%a1%e0%b8%82%e0%b8%ad%e0%b8%87%e0%b8%9a%e0%b8%b8%e0%b8%84%e0%b8%84%e0%b8%a5%e0%b8%ad%e0%b8%ad/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/289098221_586550159662695_1032763863887327249_n-300x225.jpg',
				'cats' => array(
					'knowledge',
					'general',
				),
				'date_label' => '05-07-2565',
				'views' => '2,893',
				'order' => 4,
			),
			array(
				'title' => 'เคยไหม? เวลาพบคนตาบอดจะข้ามถนน … อยากจะช่วยแต่ไม่รู้ว่าจะทำอย่างไร??',
				'excerpt' => 'เคยไหม? เวลาพบคนตาบอดจะข้ามถนน … อยากจะช่วยแต่ไม่รู้ว่าจะทำอย่างไร?? การพ…',
				'url' => 'https://dth.or.th/knowledge/https-web-facebook-com-tabodthai-photos-a-434572563305797-5424047981024872/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/284793305_5424047971024873_3993741284349771105_n-1-300x200.jpg',
				'cats' => array(
					'knowledge',
					'blind',
				),
				'date_label' => '05-07-2565',
				'views' => '5,518',
				'order' => 5,
			),
			array(
				'title' => '45 สถานพยาบาลเอกชนที่สามารถออกเอกสารรับรองความพิการ',
				'excerpt' => '๔๕ สถานพยาบาลเอกชนที่สามารถออกเอกสารรับรองความพิการ (๑) โรงพยาบาลเพชรเวช เขตห้วย…',
				'url' => 'https://dth.or.th/knowledge/45-%e0%b8%aa%e0%b8%96%e0%b8%b2%e0%b8%99%e0%b8%9e%e0%b8%a2%e0%b8%b2%e0%b8%9a%e0%b8%b2%e0%b8%a5%e0%b9%80%e0%b8%ad%e0%b8%81%e0%b8%8a%e0%b8%99/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/1-300x300.jpg',
				'cats' => array(
					'knowledge',
					'general',
				),
				'date_label' => '05-07-2565',
				'views' => '19,906',
				'order' => 6,
			),
		),
		'media' => array(
			array(
				'title' => 'สิทธิของผู้ดูแลคนพิการ',
				'excerpt' => '',
				'url' => 'https://dth.or.th/infographic/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/275229039_1594676890888765_1550337596592218467_n-300x212.jpg',
				'cats' => array(
					'rights',
				),
				'date_label' => '',
				'views' => '32,475',
				'order' => 0,
			),
			array(
				'title' => 'ที่จอดรถคนพิการ',
				'excerpt' => '',
				'url' => 'https://dth.or.th/infographic/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/273556717_1580157409007380_985939727756942970_n-300x212.jpg',
				'cats' => array(
					'rights',
				),
				'date_label' => '',
				'views' => '31,921',
				'order' => 1,
			),
			array(
				'title' => 'สิทธิค่าโดยสารอัตราพิเศษในระบบขนส่งสาธารณะ',
				'excerpt' => '',
				'url' => 'https://dth.or.th/infographic/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/275194508_1594645250891929_4929658142830719063_n-300x212.jpg',
				'cats' => array(
					'rights',
				),
				'date_label' => '',
				'views' => '28,924',
				'order' => 2,
			),
			array(
				'title' => 'ช่วยเหลือทางกฎหมายแก่คนพิการ',
				'excerpt' => '',
				'url' => 'https://dth.or.th/infographic/',
				'image' => 'https://dth.or.th/wp-content/uploads/2022/07/275425030_1598676160488838_995252658959268142_n-300x212.jpg',
				'cats' => array(
					'law',
				),
				'date_label' => '',
				'views' => '4,710',
				'order' => 3,
			),
			array(
				'title' => 'การปรับสภาพบ้านสำหรับคนพิการ 7 ขั้นตอน',
				'excerpt' => '',
				'url' => 'Pic/infographic/home-mod-7steps.jpg',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/infographic/home-mod-7steps.jpg',
				'cats' => array(
					'home',
				),
				'date_label' => 'อินโฟกราฟิก',
				'views' => '',
				'order' => 4,
			),
			array(
				'title' => 'การปรับสภาพแวดล้อมที่อยู่อาศัยสำหรับคนพิการ',
				'excerpt' => '',
				'url' => 'Pic/infographic/home-environment-2567.jpg',
				'image' => 'https://itsupport-owatmaid.github.io/dth-redesign/Pic/infographic/home-environment-2567.jpg',
				'cats' => array(
					'home',
				),
				'date_label' => 'อินโฟกราฟิก',
				'views' => '',
				'order' => 5,
			),
			array(
				'title' => 'DTH Magazine ฉบับที่ 14 — Colleague',
				'excerpt' => '',
				'url' => 'Doc/magazine/dth-magazine-vol14.pdf',
				'image' => '',
				'cats' => array(
					'magazine',
				),
				'date_label' => 'PDF · 13 MB',
				'views' => '',
				'order' => 6,
			),
			array(
				'title' => 'DTH Magazine ฉบับที่ 13 — Work Together Issue',
				'excerpt' => '',
				'url' => 'Doc/magazine/dth-magazine-vol13.pdf',
				'image' => '',
				'cats' => array(
					'magazine',
				),
				'date_label' => 'PDF · 4.2 MB',
				'views' => '',
				'order' => 7,
			),
		),
		'proposals' => array(
			array(
				'title' => 'ข้อเสนอคนพิการต่อรัฐบาล',
				'meta_label' => '24 ธันวาคม 2568 · PDF · 426 KB · ดาวน์โหลด',
				'file' => 'https://itsupport-owatmaid.github.io/dth-redesign/Doc/proposals/proposal-gov-2568.pdf',
				'gallery' => array(
					'https://itsupport-owatmaid.github.io/dth-redesign/Pic/proposals/proposal-1.jpg',
					'https://itsupport-owatmaid.github.io/dth-redesign/Pic/proposals/proposal-2.jpg',
					'https://itsupport-owatmaid.github.io/dth-redesign/Pic/proposals/proposal-3.jpg',
					'https://itsupport-owatmaid.github.io/dth-redesign/Pic/proposals/proposal-4.jpg',
				),
				'order' => 0,
			),
		),
		'pages' => array(
			'about' => array(
				'title' => 'เกี่ยวกับเรา',
				'content' => '<!-- wp:paragraph -->
<p><strong>สมาคมสภาคนพิการทุกประเภทแห่งประเทศไทย (Disabilities Thailand — DTH)</strong> เป็น<strong>องค์กรร่ม (Umbrella Organization)</strong> ของขบวนการคนพิการระดับชาติ ทำหน้าที่เป็นผู้แทนและปากเสียงของคนพิการทุกประเภท เพื่อขับเคลื่อนสิทธิ สวัสดิการ และโอกาสที่เท่าเทียม สู่การมีส่วนร่วมในสังคมอย่างเต็มที่และเสมอภาคของคนพิการทุกคน</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2>ความเป็นมา</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>สภาคนพิการทุกประเภทแห่งประเทศไทย กำเนิดขึ้นหลังปีคนพิการสากล เมื่อวันที่ 20 ตุลาคม 2526 โดยแกนนำคนพิการหลายท่านในขณะนั้น ซึ่งได้รับแรงบันดาลใจจากการเข้าร่วมประชุมสมัชชาคนพิการ</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>“คนพิการสากล” (DISABLED PEOPLE’S INTERNATIONAL) ณ ประเทศสิงคโปร์ ในปี พ.ศ. 2524 ซึ่งมีวัตถุประสงค์ (ธีม) หลัก คือ “คนพิการควรจะมีสิทธิเข้ามีส่วนร่วมในสังคมอย่างเต็มที่และเสมอภาค (Full Participation and Equality) เช่นบุคคลทั่วไปในฐานะที่เป็นส่วนหนึ่งของสังคม”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>ด้วยเหตุที่ตระหนักดีในสภาพความเป็นจริงว่าคนพิการในประเทศไทยได้ถูกละเลยทอดทิ้งจากรัฐและสังคมมาเป็นเวลานาน คนพิการไม่เคยได้มีสิทธิ และโดยที่คนพิการแต่ละประเภทในประเทศไทยมิได้รวมตัวเป็นอันหนึ่งอันเดียวกันทำให้ขาดพลังในการขับเคลื่อนนโยบายและกฎหมายที่เกี่ยวข้องกับคนพิการ</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>ดังนั้นผู้นำคนพิการประเภทต่างๆ เช่น ผู้นำสมาคมคนตาบอดแห่งประเทศไทย ผู้นำสมาคมคนหูหนวกแห่งประเทศไทย ผู้นำสมาคมคนพิการแห่งประเทศไทย และผู้นำสมาคมผู้ปกครองเพื่อคนพิการทางสติปัญญาแห่งประเทศไทย จึงได้ร่วมประชุมปรึกษาหารือกัน เพื่อจะรวมตัวกันเป็นองค์กรเดียวเพื่อทำหน้าที่เป็นผู้แทน เป็นปากเสียงให้กับคนพิการทั้งมวล โดยรณรงค์เรียกร้องให้มีกฎหมาย มีระเบียบข้อบังคับที่จะให้ประโยชน์ต่อคนพิการทุกประเภท ในที่สุดเมื่อวันที่ 20-22 ตุลาคม 2526 ที่จังหวัดเชียงใหม่ โดยมีคนพิการทุกประเภทและตัวแทนจากทั่วทุกภูมิภาคของประเทศไทยเข้าร่วมประชุมและมีมติให้จัดตั้ง “สภาคนพิการทุกประเภทแห่งประเทศไทย”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>ปัจจุบันสภาคนพิการทุกประเภทแห่งประเทศไทยเป็นองค์การขับเคลื่อนเชิงนโยบายด้านคนพิการระดับชาติ ซึ่งถูกรับรองฐานะไว้ในพระราชบัญญัติส่งเสริมและพัฒนาคุณภาพชีวิตคนพิการ พ.ศ. 2550 เป็นองค์กรร่ม (Umbrella Organization) มีสมาชิกสามัญถาวร คือ องค์การด้านคนพิการแต่ละประเภทระดับชาติ 6 องค์การ ได้แก่ สมาคมคนตาบอดแห่งประเทศไทย สมาคมคนหูหนวกแห่งประเทศไทย สมาคมคนพิการแห่งประเทศไทย สมาคมเพื่อคนพิการทางสติปัญญาแห่งประเทศไทย สมาคมเพื่อผู้บกพร่องทางจิตแห่งประเทศไทย และสมาคมผู้ปกครองบุคคลออทิซึม(ไทย) รวมทั้งมีสมาชิกสามัญทั่วไป ได้แก่ สภาคนพิการทุกประเภทประจำจังหวัดที่เป็นสาขาอยู่ใน 77 จังหวัด อีกทั้งยังมีสมาชิกวิสามัญซึ่งเป็นภาคีเครือข่ายองค์กรด้านคนพิการอื่น</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2>วัตถุประสงค์</h2>
<!-- /wp:heading -->

<!-- wp:list {"ordered":true} -->
<ol>
<!-- wp:list-item -->
<li>เสนอแนะ แก้ไขเพิ่มเติม ขับเคลื่อน และติดตามการบังคับใช้ กฎหมาย นโยบาย ยุทธศาสตร์ แผนงาน ตลอดจนพันธกรณีระหว่างประเทศ เพื่อการส่งเสริมและพัฒนาคุณภาพชีวิตคนพิการ รวมทั้งผลักดันให้มีการผนวกรวมประเด็นคนพิการเข้าสู่การพัฒนากระแสหลัก</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>เป็นสภาคนพิการทุกประเภทแห่งประเทศไทย เพื่อเสริมสร้างความเข้มแข็งและการมีธรรมาภิบาลขององค์การคนพิการแต่ละประเภทและองค์กรด้านคนพิการ</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>ส่งเสริมและสนับสนุนการพัฒนาเครือข่ายองค์กรด้านคนพิการ เพื่อให้เกิดการทำงานร่วมกันอย่างเป็นปึกแผ่นและมีเอกภาพระหว่างคนพิการแต่ละประเภท โดยเฉพาะผ่านกลไกสภาคนพิการทุกประเภทประจำจังหวัด</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>ส่งเสริมและสนับสนุนการมีส่วนร่วมขององค์การคนพิการแต่ละประเภทและองค์กรของคนพิการในฐานะเป็นหุ้นส่วนกับภาครัฐ ภาคธุรกิจเอกชน และภาคประชาสังคม ให้ได้รับการยอมรับอย่างมีศักดิ์ศรีและเท่าเทียมกัน เพื่อการพัฒนาที่ยั่งยืน</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>เสริมสร้างความเข้าใจและเจตคติเชิงสร้างสรรค์ต่อคนพิการและความพิการ</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>ทำหน้าที่พิทักษ์สิทธิคนพิการ และเป็นผู้ร้องขอหรือฟ้องคดีแทนองค์การคนพิการแต่ละประเภทหรือองค์กรด้านคนพิการเฉพาะในกรณีที่มีผลกระทบต่อคนพิการโดยรวม รวมทั้งส่งเสริมให้สมาชิกให้บริการและความช่วยเหลือต่างๆ แก่คนพิการ</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>ทำหน้าที่เป็นองค์กรประสานงานร่วมขององค์การคนพิการแต่ละประเภท รวมถึงการเข้าร่วมเป็นผู้แทนในคณะกรรมการหรือคณะอนุกรรมการตามที่กฎหมายกำหนดให้ผู้แทนองค์กรคนพิการระดับชาติเป็นกรรมการหรืออนุกรรมการ</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>ดำเนินกิจการกระจายเสียง กิจการโทรทัศน์ และกิจการสื่อสารอื่น ด้านการส่งเสริมและพัฒนาคุณภาพชีวิตของคนพิการเพื่อประโยชน์สาธารณะโดยไม่แสวงผลกำไร</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>ส่งเสริมและสนับสนุนการศึกษาวิจัยและงานวิชาการ เพื่อนำไปใช้ในการขับเคลื่อนและติดตามการบังคับใช้กฎหมายและนโยบายด้านคนพิการ</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>ไม่เกี่ยวข้องกับการเมืองและมีวัตถุประสงค์ไม่ค้ากำไร</li>
<!-- /wp:list-item -->
</ol>
<!-- /wp:list -->

<!-- wp:heading {"level":2} -->
<h2>วิสัยทัศน์</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>“สภาคนพิการทุกประเภทแห่งประเทศไทยเข้มแข็ง มีธรรมาภิบาล เป็นกลไกหลักร่วมกับองค์การคนพิการแต่ละประเภทในการขับเคลื่อนนโยบายด้านคนพิการ และเป็นหุ้นส่วนสำคัญในการพัฒนาที่ยั่งยืน”</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2>พันธกิจ</h2>
<!-- /wp:heading -->

<!-- wp:list {"ordered":true} -->
<ol>
<!-- wp:list-item -->
<li>เสริมสร้างความเข้มแข็ง ความเป็นปึกแผ่น และการมีธรรมาภิบาลของสภาคนพิการทุกประเภทแห่งประเทศไทยและสภาคนพิการทุกประเภทประจำจังหวัด</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>ขับเคลื่อนและติดตามการบังคับใช้กฎหมาย นโยบาย ยุทธศาสตร์ แผนงาน ตลอดจนพันธกรณีระหว่างประเทศ เพื่อการส่งเสริมและพัฒนาคุณภาพชีวิตคนพิการ รวมทั้งผลักดันให้มีการผนวกรวมประเด็นคนพิการเข้าสู่การพัฒนากระแสหลัก</li>
<!-- /wp:list-item -->
<!-- wp:list-item -->
<li>ส่งเสริมและสนับสนุนการมีส่วนร่วมของสภาคนพิการทุกประเภทแห่งประเทศไทยและสภาคนพิการทุกประเภทประจำจังหวัด ในฐานะเป็นหุ้นส่วนกับภาครัฐ ภาคเอกชน และภาคส่วนอื่น เพื่อการพัฒนาที่ยั่งยืน</li>
<!-- /wp:list-item -->
</ol>
<!-- /wp:list -->

<!-- wp:heading {"level":2} -->
<h2>ผลงานที่ภาคภูมิใจ</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>ด้านกฎหมาย</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong>ปี 2534</strong> สภาคนพิการฯ สามารถผลักดันพระราชบัญญัติการฟื้นฟูสมรรถภาพคนพิการ พ.ศ. 2534 ซึ่งเป็นกฎหมายฉบับแรกด้านคนพิการ ทำให้เกิดหน่วยงานและคณะกรรมการที่ทำงานเรื่องคนพิการเป็นรูปธรรม มีการจดทะเบียนและให้บริการแก่คนพิการในด้านต่างๆ เช่น การฟื้นฟูสมรรถภาพทางการแพทย์ การศึกษา การประกอบอาชีพ และการได้รับสิ่งอำนวยความสะดวก</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>ปี 2540</strong> สภาคนพิการฯ ผลักดันให้รัฐธรรมนูญปี 2540 บัญญัติเรื่องสิทธิของคนพิการไว้ได้สำเร็จ “มาตรา 55 บุคคลซึ่งพิการหรือทุพพลภาพ มีสิทธิได้รับสิ่งอำนวยความสะดวก อันเป็นสาธารณะและความช่วยเหลืออื่นจากรัฐ ทั้งนี้ ตามที่กฎหมายบัญญัติ”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>ปี 2550</strong> สภาคนพิการฯ ผลักดันให้ รัฐธรรมนูญปี 2550 บัญญัติเรื่องการห้ามเลือกปฏิบัติโดยไม่เป็นธรรมต่อบุคคลเพราะเหตุแห่ง “ความพิการ” ไว้เป็นครั้งแรกในมาตรา 30 และปฏิรูปพระราชบัญญัติการฟื้นฟูสมรรถภาพคนพิการ พ.ศ. 2534 ให้เป็นพระราชบัญญัติส่งเสริมและพัฒนาคุณภาพชีวิตคนพิการ พ.ศ. 2550 ที่เปลี่ยนจาก “ฐานคิดแบบเวทนานิยม/สงเคราะห์/ช่วยเหลือ” เป็น “ฐานสิทธิ”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>ปี 2551</strong> สภาคนพิการฯ ผลักดันให้มีการประกาศใช้ พระราชบัญญัติการจัดการศึกษาสำหรับคนพิการ พ.ศ. 2551</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>ปี 2560-2561</strong> สภาคนพิการฯ ผลักดันให้มีการแก้ไขพระราชบัญญัติลิขสิทธิ์ พ.ศ. 2537 เพื่อกำหนดให้คนพิการได้รับโอกาสอย่างเท่าเทียมกับบุคคลอื่นในการเข้าถึงงานอันมีลิขสิทธิ์ โดยให้สามารถทำซ้ำหรือดัดแปลงงานอันมีลิขสิทธิ์ เช่น วรรณกรรม ศิลปกรรม ให้อยู่ในรูปแบบที่คนพิการเข้าถึงได้ เช่น อักษรเบรลล์ ภาษามือ รวมทั้งเพื่อให้ประเทศไทยเข้าเป็นภาคีแห่งสนธิสัญญามาร์ราเคช (Marrakesh Treaty) ขององค์การทรัพย์สินทางปัญญาโลก</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>ปี 2561</strong> สภาคนพิการฯ ได้จัดทำข้อเสนอต่อร่างพระราชบัญญัติการศึกษาแห่งชาติ พ.ศ. …. ฉบับรับฟังความคิดเห็นวันที่ 15 มิถุนายน 2561 โดยคณะกรรมการอิสระเพื่อการปฏิรูปการศึกษา เพื่อขอให้ 1) ใส่คำว่า“คนพิการ” ไว้ทั้งในบทนิยามและในทุกมาตราที่เกี่ยวข้อง 2) เพิ่มศูนย์การเรียนเฉพาะความพิการ 3) กำหนดให้คนพิการสามารถเข้าถึงและใช้ประโยชน์ได้จากบริการสารสนเทศด้านการศึกษา 4) ขอให้มีการจัดชั้นเรียนในรูปแบบที่สอดคล้องกับความต้องการจำเป็นพิเศษทางการศึกษา และ 5) ขอให้บัญญัติคำว่า “ออทิสติก” ไว้ในกฎหมายอันจะช่วยให้บุคคลออทิสติกได้รับสิทธิทางการศึกษา</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3>ด้านนโยบาย</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong>ปี 2559-2561</strong> ให้คนพิการที่เป็นผู้ประกันตนตามกฎหมายประกันสังคมที่ได้รับประโยชน์ทดแทนจากการเจ็บป่วย สามารถเลือกรับบริการสาธารณสุขจากกฎหมายว่าด้วยหลักประกันสุขภาพแห่งชาติ (บัตรทอง) อย่างใดอย่างหนึ่งแทนได้</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>ปี 2560-2561</strong> สภาคนพิการฯ ผลักดันให้คนพิการและผู้ดูแลคนพิการสามารถเข้าถึง “การกู้ยืมเงินทุนเพื่อใช้ในการประกอบอาชีพ” ได้ง่ายขึ้นเร็วขึ้นไม่ติดขัด โดยผู้ขอกู้ยืมเงินทุนประกอบอาชีพเป็นรายบุคคลซึ่งเป็นคนพิการหรือผู้ดูแลคนพิการ สามารถขอกู้ยืมเงินในท้องที่ใดที่ตนได้ประกอบอาชีพอยู่อย่างแท้จริงได้ โดยไม่จำเป็นจะต้องเป็นภูมิลำเนาตามทะเบียนบ้านอีกต่อไป และให้นิติบุคคล (องค์การคนพิการแต่ละประเภท/สมาคมต่าง ๆ) สามารถค้ำประกันผู้ขอกู้ทั้งที่เป็นรายบุคคลหรือรายกลุ่มก็ได้</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3>ด้านการพัฒนาเครือข่าย</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong>ปี 2526-2560</strong> สภาคนพิการฯ ได้จัด “สมัชชาคนพิการแห่งชาติ” ต่อเนื่องมาเป็นระยะเวลาเกือบ 30 ปี โดยเป็นงานประจำปีที่ผู้นำคนพิการทั่วประเทศได้มีโอกาสมาพบปะพูดคุยแลกเปลี่ยน รวมทั้งกำหนดแนวนโยบายการทำงานของสภาคนพิการฯ ร่วมกัน เช่น ปีที่ผ่านมาเน้นเรื่องการสร้างความเข้มแข็งให้แก่สภาคนพิการจังหวัดทั้ง 77 จังหวัด</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3>ด้านพิทักษ์คุ้มครองสิทธิของคนพิการ</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong>ปี 2560-2561</strong> สภาคนพิการฯ ฟ้องศาลปกครองกลางให้เพิกถอนคำสั่งของกระทรวงการคลังที่ขอให้กองทุนส่งเสริมและพัฒนาคุณภาพชีวิตคนพิการนำเงินสภาพคล่องส่วนที่เกินความจำเป็นของทุนหมุนเวียนส่งคลังเป็นรายได้แผ่นดิน จำนวน 2,000 ล้านบาท</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3>ด้านต่างประเทศ</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><strong>ปี 2559</strong> สภาคนพิการฯ ได้ร่วมมือกับมูลนิธิสถาบันวิจัยเพื่อการพัฒนาคนพิการ ประเทศไทย จัดทำ”รายงานคู่ขนานการปฏิบัติตามอนุสัญญาว่าด้วยสิทธิคนพิการของประเทศไทย” ซึ่งประเทศไทยเป็นประเทศแรกในอาเซียนที่จัดทำรายงานคู่ขนาน และได้ไปนำเสนอรายงานดังกล่าวต่อคณะกรรมการว่าด้วยสิทธิคนพิการแห่งสหประชาชาติ ที่นครเจนีวา สวิสเซอร์แลนด์ เมื่อวันที่ 30 มีนาคม 2559</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":2} -->
<h2>องค์การสมาชิก 6 องค์การ</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>สมาคมคนตาบอดแห่งประเทศไทย</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>สมาคมผู้ปกครองคนพิการทางสติปัญญาแห่งประเทศไทย</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>สมาคมผู้ปกครองบุคคลออทิซึม (ไทย)</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>สมาคมคนหูหนวกแห่งประเทศไทย</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>สมาคมคนพิการแห่งประเทศไทย</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>สมาคมเพื่อผู้บกพร่องทางจิตแห่งประเทศไทย</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>อยากร่วมงานหรือสอบถามข้อมูลเพิ่มเติม?</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>ติดต่อสมาคมสภาคนพิการทุกประเภทแห่งประเทศไทย</p>
<!-- /wp:paragraph -->',
			),
			'regulations' => array(
				'title' => 'ข้อบังคับ ระเบียบ และเอกสารดาวน์โหลด',
				'content' => '<!-- wp:heading {"level":2} -->
<h2>เอกสารดาวน์โหลด</h2>
<!-- /wp:heading -->',
			),
		),
		'category_names' => array(
			'pr' => 'ข่าวประชาสัมพันธ์',
			'activity' => 'กิจกรรม',
			'report' => 'รายงานประจำปี',
			'knowledge' => 'สาระน่ารู้',
			'health' => 'สุขภาพ',
			'general' => 'ทั่วไป',
			'blind' => 'สมาคมคนตาบอดแห่งประเทศไทย',
			'rights' => 'อินโฟกราฟิกสิทธิ',
			'law' => 'กฎหมาย',
			'magazine' => 'DTH-Magazine',
			'video' => 'วิดีโอ',
			'infographic' => 'อินโฟกราฟิก',
			'download' => 'เอกสารดาวน์โหลด',
		),
	);
}
