<?php
/** ข้อมูลเริ่มต้นจังหวัด (seed) — สร้างอัตโนมัติจาก provinces.html */
if ( ! defined( 'ABSPATH' ) ) { exit; }
function dth_province_seed_data() {
	return array(
		array('region'=>'north','name'=>'เชียงใหม่','chair'=>'ผศ.ดวงพร อ่อนหวาน','dtype'=>'ออทิสติก','phone'=>'089-7004396'),
		array('region'=>'north','name'=>'เชียงราย','chair'=>'นายพรศักดิ์ สีสม','dtype'=>'สายตา','phone'=>'061-9724715'),
		array('region'=>'north','name'=>'แพร่','chair'=>'นางสาวนิตยา ท้าวทา','dtype'=>'การได้ยิน','phone'=>'098-3603252'),
		array('region'=>'north','name'=>'แม่ฮ่องสอน','chair'=>'นายเรวัตร วงศ์ศักดิ์ศรี','dtype'=>'ออทิสติก','phone'=>'081-9982268'),
		array('region'=>'north','name'=>'น่าน','chair'=>'นายบุญเริ่ม ทิศานุรักษ์','dtype'=>'สายตา','phone'=>'063-7962508'),
		array('region'=>'north','name'=>'กำแพงเพชร','chair'=>'นายสีมาลา เอี่ยมศรี','dtype'=>'เคลื่อนไหว','phone'=>'086-9378535'),
		array('region'=>'north','name'=>'ตาก','chair'=>'พันโทสุชาติ โท่มาก','dtype'=>'สติปัญญา','phone'=>'091-0035708'),
		array('region'=>'north','name'=>'นครสวรรค์','chair'=>'นายนิภัทร ทองเงิน','dtype'=>'การได้ยิน','phone'=>'061-6527696'),
		array('region'=>'north','name'=>'พะเยา','chair'=>'นายเต็ม มณีวรรณ์','dtype'=>'จิตใจ','phone'=>'085-7070723'),
		array('region'=>'north','name'=>'พิจิตร','chair'=>'นางสาวรินทร์ลภัส บัณฑิตสกุลชัย','dtype'=>'เคลื่อนไหว','phone'=>'095-453 0899'),
		array('region'=>'north','name'=>'พิษณุโลก','chair'=>'นายอิศรุจน์ อิศรางกรู ณ อยุธยา','dtype'=>'การได้ยิน','phone'=>'095-6295107'),
		array('region'=>'north','name'=>'ลำปาง','chair'=>'นางกิตติยา รัตนพรรณ','dtype'=>'สติปัญญา','phone'=>'096-6988368'),
		array('region'=>'north','name'=>'ลำพูน','chair'=>'นางชลธิชา พิพัฒนไมตรี','dtype'=>'การได้ยิน','phone'=>'083-2049153'),
		array('region'=>'north','name'=>'สุโขทัย','chair'=>'นายไพรวัลย์ ถึงจีน','dtype'=>'การได้ยิน','phone'=>'062-1576202'),
		array('region'=>'north','name'=>'อุตรดิตถ์','chair'=>'นายสมพล พงษ์พันธ์','dtype'=>'การได้ยิน','phone'=>'082-1700425'),
		array('region'=>'north','name'=>'อุทัยธานี','chair'=>'นายสุนันท์ แซ่โล้ว','dtype'=>'เคลื่อนไหว','phone'=>'097-9311146'),
		array('region'=>'isan','name'=>'เลย','chair'=>'นายสีหนารถ อินทร์จา','dtype'=>'สายตา','phone'=>'087-0454146'),
		array('region'=>'isan','name'=>'กาฬสินธุ์','chair'=>'นายฉลาด นะตะวัน','dtype'=>'สายตา','phone'=>'080-6232328'),
		array('region'=>'isan','name'=>'ขอนแก่น','chair'=>'นายอาทิตย์ เกตุโท','dtype'=>'การได้ยิน','phone'=>'098-5906696'),
		array('region'=>'isan','name'=>'ชัยภูมิ','chair'=>'นางจินตนา หล้าแก้ว','dtype'=>'ออทิสติก','phone'=>'080-4667837'),
		array('region'=>'isan','name'=>'นครพนม','chair'=>'นางสาวนิลวรรณ ปิติพัฒน์','dtype'=>'การได้ยิน','phone'=>'092-3155549'),
		array('region'=>'isan','name'=>'นครราชสีมา','chair'=>'นางสาวรัตนา สีนาค','dtype'=>'การได้ยิน','phone'=>'091-8280793'),
		array('region'=>'isan','name'=>'บึงกาฬ','chair'=>'นางผ่องศรี โพธิเสน','dtype'=>'เคลื่อนไหว','phone'=>'090-7990622'),
		array('region'=>'isan','name'=>'บุรีรัมย์','chair'=>'นายวิสิทธิ์ จันทร์สิงห์','dtype'=>'จิตใจ','phone'=>'099-0757671'),
		array('region'=>'isan','name'=>'มหาสารคาม','chair'=>'นายทรงยศ วันสา','dtype'=>'การได้ยิน','phone'=>'098-6174534'),
		array('region'=>'isan','name'=>'มุกดาหาร','chair'=>'นายสุชาติ คนเพียร','dtype'=>'สายตา','phone'=>'098-5595672'),
		array('region'=>'isan','name'=>'ยโสธร','chair'=>'นางสาวชุติมา ศรีทราไชย','dtype'=>'เคลื่อนไหว','phone'=>'081-8787619'),
		array('region'=>'isan','name'=>'ร้อยเอ็ด','chair'=>'นางศุภนุช เชิงหอม','dtype'=>'สติปัญญา','phone'=>'099-5087991'),
		array('region'=>'isan','name'=>'ศรีสะเกษ','chair'=>'นายจีระศักดิ์ พรหมทา','dtype'=>'การได้ยิน','phone'=>'097-1466033'),
		array('region'=>'isan','name'=>'สกลนคร','chair'=>'นายปัญญา จันทะเสน','dtype'=>'สายตา','phone'=>'099-6678322'),
		array('region'=>'isan','name'=>'สุรินทร์','chair'=>'นางสาวจุฑาภัทร โนนใหญ่','dtype'=>'สติปัญญา','phone'=>'062-4647081'),
		array('region'=>'isan','name'=>'หนองคาย','chair'=>'นายชยุต มณีรัตน์','dtype'=>'เคลื่อนไหว','phone'=>'084-9576554'),
		array('region'=>'isan','name'=>'อำนาจเจริญ','chair'=>'นางนุจรินทร์ ถือสัตย์','dtype'=>'สติปัญญา','phone'=>'098-5849345'),
		array('region'=>'isan','name'=>'อุดรธานี','chair'=>'นางสาวยุวดี เพ็ชรพลอย','dtype'=>'การได้ยิน','phone'=>'093-8209958'),
		array('region'=>'isan','name'=>'อุบลราชธานี','chair'=>'นางสาวชนิกูล สวัสดิ์พันธ์','dtype'=>'เคลื่อนไหว','phone'=>'089-0984566'),
		array('region'=>'central','name'=>'เพชรบุรี','chair'=>'นางสาวศิรินันท์ นิลสุข','dtype'=>'เคลื่อนไหว','phone'=>'089-9139713'),
		array('region'=>'central','name'=>'กรุงเทพมหานคร','chair'=>'นางสาวเพ็ญนภา นันทดิลก','dtype'=>'สติปัญญา','phone'=>'081-8273475'),
		array('region'=>'central','name'=>'จันทบุรี','chair'=>'นางยุพยง วณอังศุธร','dtype'=>'การได้ยิน','phone'=>'084-9288762'),
		array('region'=>'central','name'=>'ฉะเชิงเทรา','chair'=>'นางนภาพร สวนเลิศ','dtype'=>'การได้ยิน','phone'=>'095-9066896'),
		array('region'=>'central','name'=>'ชลบุรี','chair'=>'นายณรงค์ ไปวันเสาร์','dtype'=>'เคลื่อนไหว','phone'=>'081-6691111'),
		array('region'=>'central','name'=>'นครนายก','chair'=>'นางสาวนารีรัตน์ รสหอม','dtype'=>'สายตา','phone'=>'089-0955209'),
		array('region'=>'central','name'=>'นครปฐม','chair'=>'นางจินดา ดีสุกใส','dtype'=>'จิตใจ','phone'=>'095-5482262'),
		array('region'=>'central','name'=>'นนทบุรี','chair'=>'นายพรทร ขุนสะอาด','dtype'=>'สติปัญญา','phone'=>'081-9289268'),
		array('region'=>'central','name'=>'ปทุมธานี','chair'=>'นางวาสนา สำลีรัตน์','dtype'=>'ออทิสติก','phone'=>'089-7817050'),
		array('region'=>'central','name'=>'ปราจีนบุรี','chair'=>'นายสุชาติ ห้วยแก้ว','dtype'=>'สายตา','phone'=>'083-0498744'),
		array('region'=>'central','name'=>'พระนครศรีอยุธยา','chair'=>'นางสาวชุตินันท์ พุ่มพฤกษ์','dtype'=>'จิตใจ','phone'=>'099-1748529'),
		array('region'=>'central','name'=>'ระยอง','chair'=>'นายสมศักดิ์ จันทร์พราหมณ์','dtype'=>'เคลื่อนไหว','phone'=>'087-0396633'),
		array('region'=>'central','name'=>'ราชบุรี','chair'=>'นางวรวรรณ องค์อภิชาติ','dtype'=>'การได้ยิน','phone'=>'092-2522404'),
		array('region'=>'central','name'=>'สมุทรปราการ','chair'=>'ดร. สิงห์คำ มณีจันสุข','dtype'=>'เคลื่อนไหว','phone'=>'081-8319544'),
		array('region'=>'central','name'=>'สมุทรสงคราม','chair'=>'นางนฤมล เอมมาวัฒน์','dtype'=>'สติปัญญา','phone'=>'080-2315246'),
		array('region'=>'central','name'=>'สมุทรสาคร','chair'=>'นายเกษม จันทร์คง','dtype'=>'เคลื่อนไหว','phone'=>'089-2225372'),
		array('region'=>'central','name'=>'สระแก้ว','chair'=>'นายวรพงศ์ วงษ์ศรีแก้ว','dtype'=>'การได้ยิน','phone'=>'064-7795571'),
		array('region'=>'central','name'=>'สิงห์บุรี','chair'=>'นายเฉลิมพร มั่นคง','dtype'=>'การได้ยิน','phone'=>'091-7814569'),
		array('region'=>'central','name'=>'อ่างทอง','chair'=>'นายทศพร บินกาซัน','dtype'=>'จิตใจ','phone'=>'080-1098396'),
		array('region'=>'south','name'=>'กระบี่','chair'=>'นายประดิษฐ์ แซ่ด่าน','dtype'=>'สายตา','phone'=>'088-7906649'),
		array('region'=>'south','name'=>'ชุมพร','chair'=>'นางจินตนา เล่งระบำ','dtype'=>'สติปัญญา','phone'=>'095-0157993'),
		array('region'=>'south','name'=>'ตรัง','chair'=>'นางณัชชา กู้สุจริต','dtype'=>'การได้ยิน','phone'=>'081-0822459'),
		array('region'=>'south','name'=>'นครศรีธรรมราช','chair'=>'นายธนภณ ภควัตเกศกุล','dtype'=>'ออทิสติก','phone'=>'081-8090864'),
		array('region'=>'south','name'=>'นราธิวาส','chair'=>'นายอับดุลเลาะ มะจำ','dtype'=>'สายตา','phone'=>'084-3968238'),
		array('region'=>'south','name'=>'ปัตตานี','chair'=>'นายอาหามะ มะหาจิ','dtype'=>'สายตา','phone'=>'080-7086963'),
		array('region'=>'south','name'=>'พังงา','chair'=>'นายสุรเชษฐ์ แอนุ้ย','dtype'=>'การได้ยิน','phone'=>'096-8107143'),
		array('region'=>'south','name'=>'พัทลุง','chair'=>'นายบุญสิทธิ์ หนูแสง','dtype'=>'สายตา','phone'=>'085-1211005'),
		array('region'=>'south','name'=>'ภูเก็ต','chair'=>'นางณัจฉรียา ชูแก้ว','dtype'=>'สติปัญญา','phone'=>'082-8243514'),
		array('region'=>'south','name'=>'ยะลา','chair'=>'นางสาวซูรียะห์ เซ็งยี','dtype'=>'การได้ยิน','phone'=>'061-6805402'),
		array('region'=>'south','name'=>'ระนอง','chair'=>'นายกฤตภาส เอกโอฬารกุล','dtype'=>'ออทิสติก','phone'=>'062-5364449'),
		array('region'=>'south','name'=>'สงขลา','chair'=>'นายประเสริฐ ณรงค์กูล','dtype'=>'การได้ยิน','phone'=>'080-1475486'),
		array('region'=>'south','name'=>'สตูล','chair'=>'นายอภิเดช พรหมเมฆ','dtype'=>'การได้ยิน','phone'=>'088-7854022'),
		array('region'=>'south','name'=>'สุราษฏร์ธานี','chair'=>'นายจำนงค์ เต๊ะปู','dtype'=>'การได้ยิน','phone'=>'089-8673192'),
	);
}
